# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Tell Travis CI we're using PHP
language: php

# Tell Travis CI which distro to use
dist: trusty

# Configure caches
cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: 5.3
      env: WP_VERSION=latest
      dist: precise

install:
  - composer install
  - bash bin/install-wp-tests.sh
  - export BP_SRC_DIR=/tmp/bp-src/
  - svn co --ignore-externals https://buddypress.svn.wordpress.org/trunk/src $BP_SRC_DIR

before_script:
  - composer validate

script:
  - bash bin/install-wp-tests.sh

notifications:
  email:
    on_success: never
    on_failure: change
